### ISSUE TITLE
Computing the determinant of a 6x6 matrix takes a long time

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcMatrix#6]
Computing the determinant of a 6x6 matrix bumps my PlcTask from `788` to `15222` micro seconds.

Maybe there is a bunch of copies made using the recursion from [here](https://github.com/BurksEngineering/TcMatrix/blob/main/TcMatrix/TcMatrix/POUs/Functions/Matrix/Matrix_DeterminateSquare.TcPOU#L34).

![image](https://user-images.githubusercontent.com/32679594/229925463-2f83d147-dc84-4c6e-af79-5035eaf3adcb.png)

**Comment by BurksEngineering** [comment]
Yeah, 6x6 is pretty big! I'm surprised you didn't run out of stack memory - the default allocation is very small. I don't know if there are smarter determinant calculation algorithms out there, but this one was really easy to implement with the existing tools and functions I had.

If you are trying to invert a matrix or solve a series of differential equations then maybe [UV Decomposition](https://en.wikipedia.org/wiki/Matrix_decomposition) would be a better approach. Feel free to code something up and submit a pull request!

Alternately, you could try to make a separate much slower task to do the 6x6 determinant calculation, then manage coordinating/synchronizing with your real-time task when a new solution is available.
