### ISSUE TITLE
Publish on Twinpack

### ISSUE THREAD

**Issue by beslst** [BurksEngineering/TcMatrix#9]
Hi! We implemented a package manager for TwinCAT, similarly to nuget.

https://github.com/zeugwerk/twinpack

It is integrated in TcXAEShell and Visual Studio and also offers a simple command line interface for downloading and uploading packages on CI environments. Ultimately we want to make DevOps more accessible in the PLC world and having an open source package manager is our first step towards this goal.

Would you upload TcMatrix (and TcTransform)  to Twinpack to facility the installation of it for TwinCAT users?

**Comment by BurksEngineering** [comment]
These libraries are all under the MIT license, so feel free to compile and include them yourself. I don't want the responsibility of keeping twinpack up to date, but I don't mind it being available.

I don't know what kind of information is added to a twinpack project that isn't in a standard twincat "*.library" file, but the manual step of doing things in visual studio every time the version is changed seems cumbersome. If you haven't checked out the way the arduino library stuff works you should give this a read: https://github.com/arduino/library-registry/blob/main/FAQ.md#readme . Basically, they pull the code straight from your latest 'release' on github automatically (or if you do a pull request for an update) as long as your repository is well-formatted and passes some tests. Contributors don't need to think about or know about any package managers when they push a new release.

I don't know how nuget works under the hood, but having a way for Twinpack to *pull* the code on release instead of requiring library owners to *push* the code seems way more sustainable. Let me know if you go down this path and I will be happy to include some kind of 'twinpack.properties' file in the root for you! I'll ping you on the SASE slack to see if you want to chat more about this.

**Comment by beslst** [comment]
> These libraries are all under the MIT license, so feel free to compile and include them yourself. I don't want the responsibility of keeping twinpack up to date, but I don't mind it being available.

Appreciated, not really what we want to achieve for the community here though

> I don't know how nuget works under the hood, but having a way for Twinpack to pull the code on release instead of requiring library owners to push the code seems way more sustainable.

Actually the only step you have to do is setting the version in the "Twinpack Publish dialog" you are currently uploading **if** the version in the plcproj is already available on Twinpack (as nuget we don't allow overriding package). Other information is optional, has to filled in only once, we don't require any meta files like a properties file and no other manual steps in Visual Studio are needed.

I understand that you would like to automate this stuff with i.e. a github action. So far we only do automatic building, testing and uploading the artifact to github (https://github.com/Zeugwerk/zkbuild-action), but it's a good idea to also add uploading to Twinpack to this. I am not in SASE, but I might do a pullrequest on this or ask a colleague to contact you there  ...

Anyway, thanks for your feedback!

**Comment by BurksEngineering** [comment]
From looking through the twinpack code (thank you for making it open source!) it seems like you are very close to being able to just pull a *.library file and some license info from github releases automatically: https://github.com/Zeugwerk/Twinpack/blob/main/documentation/twinpack-server.md

I think I even saw some properties in there related to repositories, branches, and releases? let me know if you want help developing a script to update libraries based on github releases!

**Comment by beslst** [comment]
Only pulling a library file from GitHub is unfortunately not in option (would be so much easier though …). The format is not documented and we can’t rely on the tag matching the version in the library file and we don’t want libraries that don’t pass at least check-all-objects (TwinCAT happily creates library files that don’t …)

We do have fully automated pipelines for our own stuff where every tag is uploaded directly to Twinpack. We also made it partly available for everybody with zkbuild mentioned above. Adding a “publish with twinpack” stage there isn’t very hard and we’ll implement it - expect a PR in the next days with a github workflow ;-)

Right now you would need to integrate TwinpackCli into your CI setup as we are doing it. But the point is, most open source developers don’t have virtual environments where they can host their CI/CD setup. And the runners that are available out-of-the on GitHub don’t work with TwinCAT - this is something that we want to facilitate with zkbuild and Twinpack

**Comment by BurksEngineering** [comment]
If you want to try reading a few properties from a library file you can check out this little tool I just made that might help: https://github.com/BurksEngineering/TwincatLibraryUtilities

You could do a 'happy case' pull where if the release version and twincat internal library version match you will publish a new version to your package manager (and maybe make an issue if they don't match!).

**Comment by beslst** [comment]
Nicely done, yes, this will work except for the “library should pass the check-all-objects” check.

I’ll come back to you about it. You would prefer manually creating the release and uploading the files to GitHub over a workflow that automatically builds and uploads the library if there is a new tag? I think both are valid use cases, but would personally prefer having the whole thing

**Comment by beslst** [comment]
You can look here if you want to see what I mean by having such a workflow:

https://github.com/stefanbesler/struckig/actions (i.e in the Build/Test workflow shown there)

**Comment by beslst** [comment]
Here we go ... 
I think including this workflow in your repository is doing what you wanted. It is not fully tested yet and the documentation is missing - but as it was your suggested you might want to give some feedback?

Workflow to be placed in ".github/workflows.deploy.yml" - This will automatically publish to twinpack for any release you publish, thanks to your .library parsing code.

```
name: Deploy
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  Deploy:
    name: Twinpack
    runs-on: windows-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.library"
      - uses: Zeugwerk/twinpack-action@v0.4.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }} 
```


Demo (the error is because the package is already published and we don't allow overriding)
```
https://github.com/stefanbesler/struckig/actions/runs/7085304373/job/19281776926
```

**Comment by BurksEngineering** [comment]
Wow, great job! That was a quick turnaround and it looks like its working well for you. I don't know if the magic GUID for project info will change with new TwinCAT releases, so I may need to update the code at some point.

Now that you have a way to upload libraries without any config files, would you consider automating a *pull* of the libraries instead of relying on every library to do a *push* in their workflow? That would also eliminate the need for users to make an account with your company because it lets your own repo be the authority on what libraries should be used. Maybe you can do something tricky with dependabot? Again, I definitely recommend looking at how Arduino set up their user contributed libraries!

**Comment by beslst** [comment]
Twinpack originates from our CI/CD pipelines where we had the necessity to have a package manager for creating snapshots and releases with internal and external dependencies - I think *push* is better suited in a CI scenario and probably the reason why all package manager I used so far do it like that - polling every hour as Arduino does it, would not be beneficial here.

I have to admit though: outside of CI pulling really seems to have has it merits. Besides a PR to the registry repo there is no interaction required from the contributor and we don’t have to hustle with authentication.
Thanks for the discussion, it was really helpful to have some other perspective. You actually convinced me to implement something like that.

I will test the feature with TcMatrix if you are ok with it

**Comment by beslst** [comment]
One more thing, it would be great to also get references that are used in the .library so this information can be available to Twinpack as well. Do you know how to get this information out of the library file or have some general strategy how we might find out where this is stored?

**Comment by BurksEngineering** [comment]
> Besides a PR to the registry repo there is no interaction required from the contributor and we don’t have to hustle with authentication

That is a huge benefit IMO, especially if you are trying to rally a bunch of independent creators to host their content on your company's manager despite a first-party manager getting released by TwinCAT.

I'm glad I could help you consider some alternatives, and you are welcome to use any of my projects in your testing and package manager. Let me know if you ever needs some metadata or the library reader breaks or something.

I just updated the library reader to include dependencies. I'm less optimistic about the robustness of this implementation so if you find an incompatible library file please send it my way for examination. Good luck!

**Comment by beslst** [comment]
Congratulations, you are live on Twinpack :-)
https://github.com/Zeugwerk/Twinpack-Registry/blob/main/repositories.txt
https://github.com/Zeugwerk/Twinpack-Registry/actions

Again, great idea, I really like it.

> That is a huge benefit IMO, especially if you are trying to rally a bunch of independent creators to host their content on your company's manager despite a first-party manager getting released by TwinCAT.

Are you talking about the package manager that will come with 4026.xx? - We were kinda excited to use it and started developing on Twinpack after seeing that it is not really what we were expecting from a package manager. It is great for their use case, but publishing your own libraries with it seems pretty cumbersome- this might change until their release, should be any time now ;-)

![image](https://github.com/BurksEngineering/TcMatrix/assets/84121166/8b3500e2-e3f3-452d-9d22-8d7ecbcfc4e7)

**Comment by BurksEngineering** [comment]
Great job getting this working!
